### ISSUE TITLE
Inductor dashboard features tracking

### ISSUE THREAD

**Issue by huydhn** [pytorch/test-infra#4410]
Here are some of the request features to Inductor dashboard:

* [ ] Sort the results https://github.com/pytorch/test-infra/issues/4136, https://github.com/pytorch/test-infra/issues/4138
* [ ] Add full support for blueberries and dynamic subgroups
* [ ] There are many options which makes the dropdown list hard to use in small screen
* [ ] https://github.com/pytorch/test-infra/issues/4258
* [ ] Better log view and error matching for inductor benchmark jobs
* [ ] Add a toggle to show everything on the same summary page https://github.com/pytorch/test-infra/issues/4031
* [ ] https://github.com/pytorch/test-infra/issues/4002

Other bugs:
* [ ] https://github.com/pytorch/test-infra/issues/4310
* [ ] https://github.com/pytorch/test-infra/issues/4192
* [ ] https://github.com/pytorch/test-infra/issues/4123

**Comment by eellison** [comment]
Another request is an option to compare two different backends, e.g. to see which dynamic models have a significant slowdown compared to normal inductor.

**Comment by ezyang** [comment]
> Add a toggle to show everything on the same summary page https://github.com/pytorch/test-infra/issues/4031

This is the single most important thing, from the perspective of the oncall

**Comment by huydhn** [comment]
cc @yangw-dev as you are planning to pick up this project

**Comment by yangw-dev** [comment]
sounds good! thx!

**Comment by yangw-dev** [comment]
> > Add a toggle to show everything on the same summary page #4031
> 
> This is the single most important thing, from the perspective of the oncall
Implemented
cc: @ezyang

**Comment by ezyang** [comment]
Oh, there's another problem, which is that there are also a lot of configs (inference/training, the difference dtypes), and being able to see the graphs + these in one page also would help the oncall a lot.

**Comment by yangw-dev** [comment]
> there are also a lot of configs (inference/training, the difference dtypes), and being able to see the graphs + these in one page also would help the oncall a lot.
Hi, thank you! Is there any issue is created for this? Mind provide the issue, and add some description(what to expect) would be super helpful! So we can add the issue to the list :)! @ezyang

**Comment by huydhn** [comment]
> Hi, thank you! Is there any issue is created for this? Mind provide the issue, and add some description(what list of things to expect) would be super helpful! So we can track the work!

There is no issue for this atm, but please feel free to create one.  I think the ask here is to see if we can remove the precision and mode pickers so that we can have all charts in one big page.  You did this for the suite picker in https://github.com/pytorch/test-infra/pull/6009.

On the other hand, I think adding more charts blindly would not be ideal. I'm thinking maybe we could show different precision dtypes in the same chart/table to start with.
